---
AWSTemplateFormatVersion: '2010-09-09'
Description: Custom Cloudformation Reclaim Provider to reclaim existing resources.
Parameters:
  S3BucketName:
    Type: String

Resources:
  Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref S3BucketName
