---
AWSTemplateFormatVersion: '2010-09-09'
Description: Demo Reclaim Provider for S3 Bucket and ECR Repository
Parameters:
  BucketName:
    Type: String
  RepositoryName:
    Type: String

Resources:
  Bucket:
    Type: Custom::ReclaimS3Bucket
    Properties:
      BucketName: !Ref BucketName
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:cfn-reclaim-provider-function'

  BucketPolicy1:
    Type: Custom::ReclaimS3BucketPolicyStatement
    DependsOn:
      - Bucket
    Properties:
      Bucket: !Ref BucketName
      PolicyStatement:
        Sid: "bucket-policy-1"
        Effect: "Allow"
        Action:
          - "s3:GetObject"
        Resource: !Sub "arn:aws:s3:::${BucketName}/abcx"
        Principal:
          AWS: "*"
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:cfn-reclaim-provider-function'

  BucketPolicy2:
    Type: Custom::ReclaimS3BucketPolicyStatement
    DependsOn:
      - Bucket
    Properties:
      Bucket: !Ref BucketName
      PolicyStatement:
        Sid: "bucket-policy-2"
        Effect: "Allow"
        Action:
          - "s3:GetObject"
        Resource: !Sub "arn:aws:s3:::${BucketName}/b"
        Principal:
          AWS: "*"
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:cfn-reclaim-provider-function'

  Repository:
    Type: Custom::ReclaimECRRepository
    Properties:
      RepositoryName: !Ref RepositoryName
      ServiceToken: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:cfn-reclaim-provider-function'
